<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreIdentificationRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */


    public function rules(): array
    {
        return [
            // 'administrateur_id' => 'nullable|exists:administrateurs,id',
            'chambre_regionale_id' => 'required|exists:chambre_regionales,id',
            'type_entreprise_id' => 'required|exists:type_entreprises,id',
            // 'numero_identification' => 'nullable|string|unique:identifications,numero_identification',
            'denomination_entreprise' => 'required|string|max:255',
            'adresse_postale' => 'nullable|string|max:255',
            'contact_entreprise' => 'required|string|max:255',
            'email_entreprise' => 'nullable|string|email|max:255',
            'registre_entreprise' => 'required|string|max:255',
            'numero_registre' => 'required|string|max:255',
            'regime_fiscal' => 'required|string|max:255',
            'nombre_associes' => 'required|integer|min:1',
            'duree_personne_morale' => 'required|integer|min:1',
            'annee_duree_personne_morale' => 'required|string|max:6',
            'capital_social' => 'required|integer|min:1',
            'numero_cnps' => 'nullable|string|max:255',
            'numero_compte_contribuable' => 'required|string|max:255',
            'type_activite_id' => 'required|exists:type_activites,id',
            'activite_secondaire' => 'nullable|string|max:255',
            'raison_social' => 'required|string|max:255',
            'sigle_ou_enseigne' => 'required|string|max:255',
            'objet_social' => 'required|string',
            'date_debut_activite' => 'required|date',
            'departement' => 'nullable|string|max:255',
            'sous_prefecture_id' => 'required|exists:sous_prefectures,id',
            'commune_id' => 'required|exists:communes,id',
            'quartier' => 'nullable|string|max:255',
            'village' => 'nullable|string|max:255',
            'numero_lot' => 'required|string|max:255',
            'numero_ilot' => 'required|string|max:255',
            'nombre_compagnon' => 'nullable|integer|min:0',
            'nombre_apprenti' => 'nullable|integer|min:0',
            'lien_google_map' => 'required|string',
            'nom_artisan' => 'required|string|max:255',
            'prenom_artisan' => 'required|string|max:255',
            'date_naissance_artisan' => 'required|date',
            'lieu_naissance_artisan' => 'required|string|max:255',
            'sexe_artisan' => 'required|string',
            'type_document_id' => 'required|exists:type_documents,id',
            'lien_type_document_artisan' => 'nullable|string',
            'autre_document_artisan' => 'nullable|string',
            'numero_document_artisan' => 'nullable|string|max:255',
            'lieu_delivrance_document_artisan' => 'nullable|string|max:255',
            'date_delivrance_document_artisan' => 'nullable|date',
            'nationalite_artisan' => 'nullable|string|max:255',
            'adresse_artisan' => 'required|string|max:255',
            'contact_artisan' => 'required|string|unique:identifications,contact_artisan',
            'contact_whatsapp' => 'required|string|unique:identifications,contact_whatsapp',
            'etat_civil_artisan' => 'required|string|max:255',
            'etes_gerant' => 'required|string|max:255',
            'email_artisan' => 'nullable|string|email|max:255|unique:identifications,email_artisan',
            'lien_photo_artisan' => 'nullable|string',
            'niveau_etude' => 'required|string|max:255',
            'classe' => 'nullable|string|max:255',
            'diplome_etude_obtenu' => 'nullable|string|max:255',
            'apprentissage_metier' => 'required|string|max:255',
            'niveau_metier_artisan' => 'nullable|string|max:255',
            'diplome_metier_obtenu' => 'nullable|string|max:255',
            'diplome_cnmci' => 'nullable|string|max:255',
            'nom_gerant' => 'required|string|max:255',
            'prenom_gerant' => 'required|string|max:255',
            'date_naissance_gerant' => 'required|date',
            'lieu_naissance_gerant' => 'required|string|max:255',
            'sexe_gerant' => 'required|string',
            'gerant_type_document_id' => 'required|exists:type_documents,id',
            'lien_type_document_gerant' => 'nullable|string',
            'autre_document_gerant' => 'nullable|string',
            'numero_document_gerant' => 'nullable|string|max:255',
            'lieu_delivrance_document_gerant' => 'nullable|string|max:255',
            'date_delivrance_document_gerant' => 'nullable|date',
            'nationalite_gerant' => 'required|string|max:255',
            'adresse_gerant' => 'required|string|max:255',
            'contact_gerant' => 'required|string|unique:identifications,contact_gerant',
            'contact_whatsapp_gerant' => 'required|string|unique:identifications,contact_whatsapp_gerant',
            'niveau_etude_gerant' => 'required|string|max:255',
            'classe_gerant' => 'nullable|string|max:255',
            'diplome_etude_obtenu_gerant' => 'nullable|string|max:255',
            'apprentissage_metier_gerant' => 'required|string|max:255',
            'niveau_metier_gerant' => 'nullable|string|max:255',
            'diplome_metier_obtenu_gerant' => 'required|string|max:255',
            'diplome_cnmci_gerant' => 'nullable|string|max:255',
            'etat_civil_gerant' => 'required|string|max:255',
            'email_gerant' => 'required|string|email|max:255',
            'lien_photo_gerant' => 'nullable|string',
            'declaration_maitrise_metier' => 'required|string|max:255',
            'declaration_honneur' => 'required|string|max:255',
            'accepte_confidentialite' => 'required|string|max:255',
            'signature' => 'required|string',
            // 'avis' => 'required|in:En Attente,Acceptée,Refusée',
            // 'motif_refus' => 'nullable|string|max:255',
            // 'status' => 'required|in:1,2,3',
        ];
    }


    public function messages(): array
    {
        return [
            'type_entreprise_id.required' => 'Le champ type entreprise est obligatoire.',
            'type_entreprise_id.exists' => 'Le type d\'entreprise sélectionné n\'existe pas.',
            // 'numero_identification.required' => 'Le numéro d\'identification est obligatoire.',
            // 'numero_identification.unique' => 'Le numéro d\'identification est déjà utilisé.',
            'denomination_entreprise.required' => 'La dénomination de l\'entreprise est obligatoire.',
            'contact_entreprise.required' => 'Le contact de l\'entreprise est obligatoire.',
            'email_entreprise.email' => 'L\'adresse e-mail de l\'entreprise doit être une adresse e-mail valide.',
            'registre_entreprise.required' => 'Le registre de l\'entreprise est obligatoire.',
            'numero_registre.required' => 'Le numéro de registre est obligatoire.',
            'regime_fiscal.required' => 'Le régime fiscal est obligatoire.',
            'nombre_associes.required' => 'Le nombre d\'associés est obligatoire.',
            'duree_personne_morale.required' => 'La durée de la personne morale est obligatoire.',
            'annee_duree_personne_morale.required' => 'L\'année de la durée de la personne morale est obligatoire.',
            'capital_social.required' => 'Le capital social est obligatoire.',
            'numero_compte_contribuable.required' => 'Le numéro de compte contribuable est obligatoire.',
            'type_activite_id.required' => 'Le champ type d\'activité est obligatoire.',
            'type_activite_id.exists' => 'Le type d\'activité sélectionné n\'existe pas.',
            'raison_social.required' => 'La raison sociale est obligatoire.',
            'sigle_ou_enseigne.required' => 'Le sigle ou enseigne est obligatoire.',
            'objet_social.required' => 'L\'objet social est obligatoire.',
            'date_debut_activite.required' => 'La date de début d\'activité est obligatoire.',
            'sous_prefecture_id.required' => 'Le champ sous-préfecture est obligatoire.',
            'sous_prefecture_id.exists' => 'La sous-préfecture sélectionnée n\'existe pas.',
            'commune_id.required' => 'Le champ commune est obligatoire.',
            'commune_id.exists' => 'La commune sélectionnée n\'existe pas.',
            'numero_lot.required' => 'Le numéro de lot est obligatoire.',
            'numero_ilot.required' => 'Le numéro d\'îlot est obligatoire.',
            'nom_artisan.required' => 'Le nom de l\'artisan est obligatoire.',
            'prenom_artisan.required' => 'Le prénom de l\'artisan est obligatoire.',
            'date_naissance_artisan.required' => 'La date de naissance de l\'artisan est obligatoire.',
            'lieu_naissance_artisan.required' => 'Le lieu de naissance de l\'artisan est obligatoire.',
            'sexe_artisan.required' => 'Le sexe de l\'artisan est obligatoire.',
            'type_document_id.required' => 'Le champ type de document est obligatoire.',
            'type_document_id.exists' => 'Le type de document sélectionné n\'existe pas.',
            'adresse_artisan.required' => 'L\'adresse de l\'artisan est obligatoire.',
            'contact_artisan.required' => 'Le contact de l\'artisan est obligatoire.',
            'contact_artisan.unique' => 'Le contact de l\'artisan est déjà utilisé.',
            'contact_whatsapp.required' => 'Le contact WhatsApp de l\'artisan est obligatoire.',
            'contact_whatsapp.unique' => 'Le contact WhatsApp de l\'artisan est déjà utilisé.',
            'etat_civil_artisan.required' => 'L\'état civil de l\'artisan est obligatoire.',
            'etes_gerant.required' => 'Le champ êtes-vous gérant est obligatoire.',
            'email_artisan.email' => 'L\'adresse e-mail de l\'artisan doit être une adresse e-mail valide.',
            'email_artisan.unique' => 'L\'adresse e-mail de l\'artisan est déjà utilisée.',
            'niveau_etude.required' => 'Le niveau d\'étude est obligatoire.',
            'apprentissage_metier.required' => 'Le champ apprentissage du métier est obligatoire.',
            'nom_gerant.required' => 'Le nom du gérant est obligatoire.',
            'prenom_gerant.required' => 'Le prénom du gérant est obligatoire.',
            'date_naissance_gerant.required' => 'La date de naissance du gérant est obligatoire.',
            'lieu_naissance_gerant.required' => 'Le lieu de naissance du gérant est obligatoire.',
            'sexe_gerant.required' => 'Le sexe du gérant est obligatoire.',
            'gerant_type_document_id.required' => 'Le type de document du gérant est obligatoire.',
            'nationalite_gerant.required' => 'La nationalité du gérant est obligatoire.',
            'adresse_gerant.required' => 'L\'adresse du gérant est obligatoire.',
            'contact_gerant.required' => 'Le contact du gérant est obligatoire.',
            'contact_gerant.unique' => 'Le contact du gérant est déjà utilisé.',
            'contact_whatsapp_gerant.required' => 'Le contact WhatsApp du gérant est obligatoire.',
            'contact_whatsapp_gerant.unique' => 'Le contact WhatsApp du gérant est déjà utilisé.',
            'niveau_etude_gerant.required' => 'Le niveau d\'étude du gérant est obligatoire.',
            'apprentissage_metier_gerant.required' => 'Le champ apprentissage du métier du gérant est obligatoire.',
            'diplome_metier_obtenu_gerant.required' => 'Le diplôme du métier du gérant est obligatoire.',
            'etat_civil_gerant.required' => 'L\'état civil du gérant est obligatoire.',
            'email_gerant.required' => 'L\'adresse e-mail du gérant est obligatoire.',
            'email_gerant.email' => 'L\'adresse e-mail du gérant doit être une adresse e-mail valide.',
            'declaration_maitrise_metier.required' => 'La déclaration de maîtrise du métier est obligatoire.',
            'declaration_honneur.required' => 'La déclaration sur l\'honneur est obligatoire.',
            'accepte_confidentialite.required' => 'L\'acceptation de la confidentialité est obligatoire.',
            'signature.required' => 'L\'acceptation de la confidentialité est obligatoire.',
        ];
    }
}
