<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreIdentificationRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */


    public function rules(): array
    {
        return [
            'type_entreprise_id' => 'required|integer',
            'denomination_entreprise' => 'required|string|max:50',
            'email_entreprise' => 'nullable|string|email|max:50',
            'contact_entreprise' => 'required|string|max:20',
            'registre_entreprise' => 'required|string|max:10',
            'numero_registre' => 'required|string|max:50',
            'capital_social' => 'required|integer|min:1',
            'branche_activite_id' => 'required|integer',
            'type_activite_id' => 'required|integer',
            'activite_secondaire' => 'nullable|string|max:250',
            'date_debut_activite' => 'required|string|max:10',
            'raison_social' => 'required|string|max:50',
            'sigle_ou_enseigne' => 'required|string|max:50',
            'objet_social' => 'required|string|max:50',
            'nombre_associes' => 'nullable|integer|min:1',
            'duree_personne_morale' => 'required|integer|min:1',
            'annee_duree_personne_morale' => 'required|string|max:10',
            'numero_cnps' => 'nullable|string|max:50',
            'numero_compte_contribuable' => 'required|string|max:50',
            'numero_lot' => 'required|string|max:50',
            'numero_ilot' => 'required|string|max:50',
            'regime_fiscal' => 'required|string|max:50',
            'departement' => 'nullable|string|max:50',
            'commune_id' => 'nullable|integer',
            'sous_prefecture_id' => 'nullable|integer',
            'village' => 'nullable|string|max:50',
            'quartier' => 'required|string|max:50',
            'adresse_postale' => 'required|string|max:50',
            'lien_google_map' => 'required|string',


            'nombre_compagnon' => 'nullable|integer|min:0',
            'nombre_apprenti' => 'nullable|integer|min:0',

            'nom_artisan' => 'required|string|max:20',
            'prenom_artisan' => 'required|string|max:70',
            'date_naissance_artisan' => 'required|date',
            'lieu_naissance_artisan' => 'required|string|max:50',
            'sexe_artisan' => 'required|integer|max:3',
            'type_document_id' => 'required|integer',
            'lien_type_document_artisan' => 'nullable|string',
            'autre_document_artisan' => 'nullable|string',
            'numero_document_artisan' => 'nullable|string|max:50',
            'lieu_delivrance_document_artisan' => 'nullable|string|max:50',
            'date_delivrance_document_artisan' => 'nullable|date',
            'nationalite_artisan' => 'required|string|max:30',
            'adresse_artisan' => 'required|string|max:50',
            'contact_artisan' => 'required|string|max:20',
            'contact_whatsapp' => 'required|string|max:20',
            'etat_civil_artisan' => 'required|string|max:20',
            'etes_gerant' => 'required|integer|max:2',
            'email_artisan' => 'nullable|string|max:50',
            'lien_photo_artisan' => 'nullable|string',
            'niveau_etude' => 'required|string|max:255',
            'classe' => 'nullable|string|max:30',
            'diplome_etude_obtenu' => 'nullable|string|max:255',
            'apprentissage_metier' => 'required|string|max:255',
            'niveau_metier_artisan' => 'nullable|string|max:30',
            'diplome_metier_obtenu' => 'nullable|string|max:50',
            'diplome_cnmci' => 'nullable|string|max:255',

            'nom_gerant' => 'required|string|max:20',
            'prenom_gerant' => 'required|string|max:70',
            'date_naissance_gerant' => 'required|date',
            'lieu_naissance_gerant' => 'required|string|max:50',
            'sexe_gerant' => 'required|integer',
            'gerant_type_document_id' => 'required|integer',
            'lien_type_document_gerant' => 'nullable|string',
            'autre_document_gerant' => 'nullable|string',
            'numero_document_gerant' => 'nullable|string|max:50',
            'lieu_delivrance_document_gerant' => 'nullable|string|max:50',
            'date_delivrance_document_gerant' => 'nullable|date',
            'nationalite_gerant' => 'required|string|max:30',
            'adresse_gerant' => 'required|string|max:50',
            'contact_gerant' => 'required|string|max:20',
            'contact_whatsapp_gerant' => 'required|string|max:20',
            'niveau_etude_gerant' => 'required|string|max:255',
            'classe_gerant' => 'nullable|string|max:30',
            'diplome_etude_obtenu_gerant' => 'nullable|string|max:255',
            'apprentissage_metier_gerant' => 'required|string|max:255',
            'niveau_metier_gerant' => 'nullable|string|max:30',
            'diplome_metier_obtenu_gerant' => 'required|string|max:50',
            'diplome_cnmci_gerant' => 'nullable|string|max:255',
            'etat_civil_gerant' => 'required|string|max:255',
            'email_gerant' => 'required|string|max:50',
            'lien_photo_gerant' => 'nullable|string',
            'declaration_maitrise_metier' => 'required|integer',
            'declaration_honneur' => 'required|integer',
            'accepte_confidentialite' => 'required|integer',
            'signature' => 'required|string',
        ];
    }

    public function messages()
{
    return [
        'type_entreprise_id.required' => 'Le type de l\'entreprise est obligatoire.',
        'type_entreprise_id.integer' => 'Le type de l\'entreprise doit être un entier.',
        'denomination_entreprise.required' => 'La dénomination de l\'entreprise est obligatoire.',
        'denomination_entreprise.string' => 'La dénomination de l\'entreprise doit être une chaîne de caractères.',
        'denomination_entreprise.max' => 'La dénomination de l\'entreprise ne doit pas dépasser 50 caractères.',
        'email_entreprise.string' => 'L\'email de l\'entreprise doit être une chaîne de caractères.',
        'email_entreprise.email' => 'L\'email de l\'entreprise doit être une adresse email valide.',
        'email_entreprise.max' => 'L\'email de l\'entreprise ne doit pas dépasser 50 caractères.',
        'contact_entreprise.required' => 'Le contact de l\'entreprise est obligatoire.',
        'contact_entreprise.string' => 'Le contact de l\'entreprise doit être une chaîne de caractères.',
        'contact_entreprise.max' => 'Le contact de l\'entreprise ne doit pas dépasser 20 caractères.',
        'registre_entreprise.required' => 'Le registre de l\'entreprise est obligatoire.',
        'registre_entreprise.string' => 'Le registre de l\'entreprise doit être une chaîne de caractères.',
        'registre_entreprise.max' => 'Le registre de l\'entreprise ne doit pas dépasser 10 caractères.',
        'numero_registre.required' => 'Le numéro de registre est obligatoire.',
        'numero_registre.string' => 'Le numéro de registre doit être une chaîne de caractères.',
        'numero_registre.max' => 'Le numéro de registre ne doit pas dépasser 50 caractères.',
        'capital_social.required' => 'Le capital social est obligatoire.',
        'capital_social.integer' => 'Le capital social doit être un entier.',
        'capital_social.min' => 'Le capital social doit être au moins 1.',
        'branche_activite_id.required' => 'La branche d\'activité est obligatoire.',
        'branche_activite_id.integer' => 'La branche d\'activité doit être un entier.',
        'type_activite_id.required' => 'Le type d\'activité est obligatoire.',
        'type_activite_id.integer' => 'Le type d\'activité doit être un entier.',
        'activite_secondaire.string' => 'L\'activité secondaire doit être une chaîne de caractères.',
        'activite_secondaire.max' => 'L\'activité secondaire ne doit pas dépasser 250 caractères.',
        'date_debut_activite.required' => 'La date de début d\'activité est obligatoire.',
        'date_debut_activite.string' => 'La date de début d\'activité doit être une chaîne de caractères.',
        'date_debut_activite.max' => 'La date de début d\'activité ne doit pas dépasser 10 caractères.',
        'raison_social.required' => 'La raison sociale est obligatoire.',
        'raison_social.string' => 'La raison sociale doit être une chaîne de caractères.',
        'raison_social.max' => 'La raison sociale ne doit pas dépasser 50 caractères.',
        'sigle_ou_enseigne.required' => 'Le sigle ou l\'enseigne est obligatoire.',
        'sigle_ou_enseigne.string' => 'Le sigle ou l\'enseigne doit être une chaîne de caractères.',
        'sigle_ou_enseigne.max' => 'Le sigle ou l\'enseigne ne doit pas dépasser 50 caractères.',
        'objet_social.required' => 'L\'objet social est obligatoire.',
        'objet_social.string' => 'L\'objet social doit être une chaîne de caractères.',
        'objet_social.max' => 'L\'objet social ne doit pas dépasser 50 caractères.',
        'nombre_associes.integer' => 'Le nombre d\'associés doit être un entier.',
        'nombre_associes.min' => 'Le nombre d\'associés doit être au moins 1.',
        'duree_personne_morale.required' => 'La durée de la personne morale est obligatoire.',
        'duree_personne_morale.integer' => 'La durée de la personne morale doit être un entier.',
        'duree_personne_morale.min' => 'La durée de la personne morale doit être au moins 1.',
        'annee_duree_personne_morale.required' => 'L\'année de durée de la personne morale est obligatoire.',
        'annee_duree_personne_morale.string' => 'L\'année de durée de la personne morale doit être une chaîne de caractères.',
        'annee_duree_personne_morale.max' => 'L\'année de durée de la personne morale ne doit pas dépasser 10 caractères.',
        'numero_cnps.string' => 'Le numéro CNPS doit être une chaîne de caractères.',
        'numero_cnps.max' => 'Le numéro CNPS ne doit pas dépasser 50 caractères.',
        'numero_compte_contribuable.required' => 'Le numéro de compte contribuable est obligatoire.',
        'numero_compte_contribuable.string' => 'Le numéro de compte contribuable doit être une chaîne de caractères.',
        'numero_compte_contribuable.max' => 'Le numéro de compte contribuable ne doit pas dépasser 50 caractères.',
        'numero_lot.required' => 'Le numéro de lot est obligatoire.',
        'numero_lot.string' => 'Le numéro de lot doit être une chaîne de caractères.',
        'numero_lot.max' => 'Le numéro de lot ne doit pas dépasser 50 caractères.',
        'numero_ilot.required' => 'Le numéro d\'ilot est obligatoire.',
        'numero_ilot.string' => 'Le numéro d\'ilot doit être une chaîne de caractères.',
        'numero_ilot.max' => 'Le numéro d\'ilot ne doit pas dépasser 50 caractères.',
        'regime_fiscal.required' => 'Le régime fiscal est obligatoire.',
        'regime_fiscal.string' => 'Le régime fiscal doit être une chaîne de caractères.',
        'regime_fiscal.max' => 'Le régime fiscal ne doit pas dépasser 50 caractères.',
        'departement.string' => 'Le département doit être une chaîne de caractères.',
        'departement.max' => 'Le département ne doit pas dépasser 50 caractères.',
        'commune_id.integer' => 'La commune doit être un entier.',
        'sous_prefecture_id.integer' => 'La sous-préfecture doit être un entier.',
        'village.string' => 'Le village doit être une chaîne de caractères.',
        'village.max' => 'Le village ne doit pas dépasser 50 caractères.',
        'quartier.required' => 'Le quartier est obligatoire.',
        'quartier.string' => 'Le quartier doit être une chaîne de caractères.',
        'quartier.max' => 'Le quartier ne doit pas dépasser 50 caractères.',
        'adresse_postale.required' => 'L\'adresse postale est obligatoire.',
        'adresse_postale.string' => 'L\'adresse postale doit être une chaîne de caractères.',
        'adresse_postale.max' => 'L\'adresse postale ne doit pas dépasser 50 caractères.',
        'lien_google_map.required' => 'Le lien Google Map est obligatoire.',
        'lien_google_map.string' => 'Le lien Google Map doit être une chaîne de caractères.',

        'nombre_compagnon.integer' => 'Le nombre de compagnons doit être un entier.',
        'nombre_compagnon.min' => 'Le nombre de compagnons doit être au moins 0.',
        'nombre_apprenti.integer' => 'Le nombre d\'apprentis doit être un entier.',
        'nombre_apprenti.min' => 'Le nombre d\'apprentis doit être au moins 0.',

        'nom_artisan.required' => 'Le nom de l\'artisan est obligatoire.',
        'nom_artisan.string' => 'Le nom de l\'artisan doit être une chaîne de caractères.',
        'nom_artisan.max' => 'Le nom de l\'artisan ne doit pas dépasser 20 caractères.',
        'prenom_artisan.required' => 'Le prénom de l\'artisan est obligatoire.',
        'prenom_artisan.string' => 'Le prénom de l\'artisan doit être une chaîne de caractères.',
        'prenom_artisan.max' => 'Le prénom de l\'artisan ne doit pas dépasser 70 caractères.',
        'date_naissance_artisan.required' => 'La date de naissance de l\'artisan est obligatoire.',
        'date_naissance_artisan.date' => 'La date de naissance de l\'artisan doit être une date valide.',
        'lieu_naissance_artisan.required' => 'Le lieu de naissance de l\'artisan est obligatoire.',
        'lieu_naissance_artisan.string' => 'Le lieu de naissance de l\'artisan doit être une chaîne de caractères.',
        'lieu_naissance_artisan.max' => 'Le lieu de naissance de l\'artisan ne doit pas dépasser 50 caractères.',
        'sexe_artisan.required' => 'Le sexe de l\'artisan est obligatoire.',
        'sexe_artisan.integer' => 'Le sexe de l\'artisan doit être un entier.',
        'sexe_artisan.max' => 'Le sexe de l\'artisan ne doit pas dépasser 3.',
        'type_document_id.required' => 'Le type de document est obligatoire.',
        'type_document_id.integer' => 'Le type de document doit être un entier.',


        'lien_type_document_artisan.string' => "ces une chaine",
        'prentissage_metier_gerant.required' => 'L\'apprentissage du métier par le gérant est obligatoire.',
        'apprentissage_metier_gerant.string' => 'L\'apprentissage du métier par le gérant doit être une chaîne de caractères.',
        'apprentissage_metier_gerant.max' => 'L\'apprentissage du métier par le gérant ne doit pas dépasser 255 caractères.',
        'niveau_metier_gerant.string' => 'Le niveau de métier du gérant doit être une chaîne de caractères.',
        'niveau_metier_gerant.max' => 'Le niveau de métier du gérant ne doit pas dépasser 30 caractères.',
        'diplome_metier_obtenu_gerant.required' => 'Le diplôme de métier obtenu par le gérant est obligatoire.',
        'diplome_metier_obtenu_gerant.string' => 'Le diplôme de métier obtenu par le gérant doit être une chaîne de caractères.',
        'diplome_metier_obtenu_gerant.max' => 'Le diplôme de métier obtenu par le gérant ne doit pas dépasser 50 caractères.',
        'diplome_cnmci_gerant.string' => 'Le diplôme CNMCI du gérant doit être une chaîne de caractères.',
        'diplome_cnmci_gerant.max' => 'Le diplôme CNMCI du gérant ne doit pas dépasser 255 caractères.',
        'etat_civil_gerant.required' => 'L\'état civil du gérant est obligatoire.',
        'etat_civil_gerant.string' => 'L\'état civil du gérant doit être une chaîne de caractères.',
        'etat_civil_gerant.max' => 'L\'état civil du gérant ne doit pas dépasser 255 caractères.',
        'email_gerant.required' => 'L\'email du gérant est obligatoire.',
        'email_gerant.string' => 'L\'email du gérant doit être une chaîne de caractères.',
        'email_gerant.max' => 'L\'email du gérant ne doit pas dépasser 50 caractères.',
        'lien_photo_gerant.string' => 'Le lien de la photo du gérant doit être une chaîne de caractères.',
        'declaration_maitrise_metier.required' => 'La déclaration de maîtrise du métier est obligatoire.',
        'declaration_maitrise_metier.integer' => 'La déclaration de maîtrise du métier doit être un entier.',
        'declaration_honneur.required' => 'La déclaration sur l\'honneur est obligatoire.',
        'declaration_honneur.integer' => 'La déclaration sur l\'honneur doit être un entier.',
        'accepte_confidentialite.required' => 'L\'acceptation de la confidentialité est obligatoire.',
        'accepte_confidentialite.integer' => 'L\'acceptation de la confidentialité doit être un entier.',
        'signature.required' => 'La signature est obligatoire.',
        'signature.string' => 'La signature doit être une chaîne de caractères.',
    ];
    }



}
