<?php

namespace Database\Seeders\permissions;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            'afficher la liste des administrateurs',
            'Ajouter un admininistrateur',
            'Afficher un admininistrateur',
            'Modifier un admininistrateur',
            'Supprimer un admininistrateur',
            'afficher la liste des parametres',
            'Ajouter un parametre',
            'Afficher un parametre',
            'Modifier un parametre',
            'Supprimer un parametre',
            'afficher la liste des agents',
            'Ajouter un agent',
            'Afficher un agent',
            'Modifier un agent',
            'Supprimer un agent',
            'afficher la liste des paiements',
            'Ajouter un paiement',
            'Afficher un paiement',
            'Modifier un paiement',
            'Supprimer un paiement',
            'afficher la liste des paiements initials',
            'Ajouter un paiement initial',
            'Afficher un paiement initial',
            'Modifier un paiement initial',
            'Supprimer un paiement initial',
            'afficher la liste des types de document',
            'Ajouter un type de document',
            'Afficher un type de document',
            'Modifier un type de document',
            'Supprimer un type de document',
            'afficher la liste des compagnons',
            'Ajouter un compagnon',
            'Afficher un compagnon',
            'Modifier un compagnon',
            'Supprimer un compagnon',
            'afficher la liste des apprentis',
            'Ajouter un apprenti',
            'Afficher un apprenti',
            'Modifier un apprenti',
            'Supprimer un apprenti',
            'afficher la liste des villes',
            'Ajouter une ville',
            'Afficher une ville',
            'Modifier une ville',
            'Supprimer une ville',
            'afficher la liste des artisans',
            'Ajouter un artisan',
            'Afficher un artisan',
            'Modifier un artisan',
            'Supprimer un artisan',
            'afficher la liste des actualites',
            'Ajouter une actualite',
            'Afficher une actualite',
            'Modifier une actualite',
            'Supprimer une actualite',
            'afficher la liste des chambres régionales',
            'Ajouter une chambre régionale',
            'Afficher une chambre régionale',
            'Modifier une chambre régionale',
            'Supprimer une chambre régionale',
            'afficher la liste des cotisations',
            'Ajouter une cotisation',
            'Afficher une cotisation',
            'Modifier une cotisation',
            'Supprimer une cotisation',
            'afficher la liste des branche d\'activités',
            'Ajouter un branche d\'activite',
            'Afficher un branche d\'activite',
            'Modifier un branche d\'activite',
            'Supprimer un branche d\'activite',
            'afficher la liste des documents de type demande',
            'Ajouter un document au type demande',
            'Afficher un document au type demande',
            'Modifier un document au type demande',
            'Supprimer un document au type demande',
            'afficher la liste des types de demandes',
            'Ajouter un type demande',
            'Afficher un type demande',
            'Modifier un type demande',
            'Supprimer un type demande',
            'afficher la liste des groupes',
            'Ajouter un groupe',
            'Afficher un groupe',
            'Modifier un groupe',
            'Supprimer un groupe',
            'afficher la liste des taxes',
            'Ajouter une taxe',
            'Afficher une taxe',
            'Modifier une taxe',
            'Supprimer une taxe',
            'afficher la liste des demandes',
            'Ajouter une demande',
            'Afficher une demande',
            'Modifier une demande',
            'Supprimer une demande',
            'afficher la liste des sous-préfectures',
            'Ajouter une sous-prefecture',
            'Afficher une sous-prefecture',
            'Modifier une sous-prefecture',
            'Supprimer une sous-prefecture',
            'afficher la liste des communes',
            'Ajouter une commune',
            'Afficher une commune',
            'Modifier une commune',
            'Supprimer une commune',
            'afficher la liste des identifications',
            'Ajouter une identification',
            'Afficher une identification',
            'Modifier une identification',
            'Supprimer une identification',
            'afficher la liste des slides',
            'Ajouter un slide',
            'Afficher un slide',
            'Modifier un slide',
            'Supprimer un slide',
            'afficher la liste des types de formations',
            'Ajouter un type formation',
            'Afficher un type formation',
            'Modifier un type formation',
            'Supprimer un type formation',
            'afficher la liste des formations',
            'Ajouter une formation',
            'Afficher une formation',
            'Modifier une formation',
            'Supprimer une formation',
            'afficher la liste des facturations',
            'Ajouter une facturation',
            'Afficher une facturation',
            'Modifier une facturation',
            'Supprimer une facturation',
            'afficher la liste des pénalités',
            'Ajouter une penalite',
            'Afficher une penalite',
            'Modifier une penalite',
            'Supprimer une penalite',
            'afficher la liste des types d\'activités',
            'Ajouter un type activite',
            'Afficher un type activite',
            'Modifier un type activite',
            'Supprimer un type activite',
            'afficher la liste des types d\'entreprises',
            'Ajouter un type entreprise',
            'Afficher un type entreprise',
            'Modifier un type entreprise',
            'Supprimer un type entreprise',
            'afficher la liste des activités artisans',
            'Ajouter une activité artisan',
            'Afficher une activité artisan',
            'Modifier une activité artisan',
            'Supprimer une activité artisan',
            'afficher la liste des carte membres',
            'Ajouter une carte membre',
            'Afficher une carte membre',
            'Modifier une carte membre',
            'Supprimer une carte membre',
        ];

        foreach ($permissions as $permission) {
            Permission::create([
                'name' => $permission,
                'guard_name' => 'web',
            ]);
        }
    }
}
