<?php

namespace App\Models\New;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class cIdentifications extends Model
{
    protected $table = "CNMCI_Identifications";
    protected $primaryKey = "ID_IDENTIFICATIONS";
    public $timestamps = true;
  protected $fillable = [

        "ID_IDENTIFICATIONS" ,
        "ID_ADMINISTRATEUR" ,
        "ID_CHAMBRE_REGION",
        "ID_TYPE_ENTREPRISES" ,
        'ID_BRANCHES',
        "NUMERO_IDENT"  ,
        "DENOMINATION"  ,
        "ADRESSE_POSTAL"  ,
        "CONTACT"  ,
        "ADR_EMAIL"  ,
        "TYPE_REGISTRE"  ,
        "NUMERO_REGISTRE"  ,
        "REGIME_FISCALE"  ,
        "NB_ASSOCIES" ,
        "DUREE_PERS_MORAL" ,
        "TYPE_DUREE" ,
        "CAPITAL_SOCIAL" ,
        "NUMERO_CNPS"  ,
        "NUM_COMPTE_CONT"  ,
        "ID_TYPE_ACTIVITES" ,
        "ACTIVITE_SECONDAIRE"  ,
        "RAISON_SOCIALE"  ,
        "SIGLE"  ,
        "OBJET_SOCIAL"  ,
        "DATE_DEBT_ACTIVITE"  ,
        "LIB_DEPARTEMENT"  ,
        "ID_SOUS_PREFECTURE" ,
        "ID_COMMUNE" ,
        "QUARTIER"  ,
        "VILLAGE"  ,
        "NUM_LOT"  ,
        "NUM_ILOT"  ,
        "NB_COMPAGNON" ,
        "NB_APPRENTIS" ,
        "LIEN_MAP"  ,
        "NOM_ART"  ,
        "PRENOMS_ARTIS" ,
        "DATE_NAISS_ARTIS"  ,
        "LIEU_NAISS_ARTIS"  ,
        "CIVILITE_ARTIS" ,
        "ID_TYPE_DOCS_ARTIS" ,
        "LIEN_TYPE_DOCS_ARTIS"  ,
        "AUTRE_DOCS_ARTIS"  ,
        "NUM_DOCS_ARTIS"  ,
        "LIEU_DELIVRE_DOCS_ARTIS"  ,
        "DATE_DELIVRE_DOCS_ARTIS"  ,
        "NATIONALITE_ARTIS"  ,
        "ADRESSE_ARTIS"  ,
        "CONTACT_ARTIS"  ,
        "CONTACT_WHATSAPP_ARTIS"  ,
        "ETAT_CIVIL_ARTIS"  ,
        "EST_GERANT" ,
        "ADR_EMAIL_ARTIS"  ,
        "AVATAR_ARTIS"  ,
        "NIVEAU_ETUDE_ARTIS"  ,
        "CLASSE_ARTIS"  ,
        "DIPLOME_OBT_ARTIS"  ,
        "APPRENTISS_MET_ARTIS"  ,
        "NIVEAU_METIER_ARTIS"  ,
        "DIPLOME_METIER_OBT_ARTIS"  ,
        "DIPLOME_CNMCI_ARTIS"  ,
        "NOM_GERAN"  ,
        "PRENOM_GERAN" ,
        "DATE_NAI_GERAN"  ,
        "LIEU_NAISS_GERAN"  ,
        "CIVILITE_GERAN" ,
        "ID_TYPE_DOCS_GERAN" ,
        "LIEN_TYPE_DOCS_GERAN"  ,
        "DATE_DELIVRE_DOCS_GERAN"  ,
        "LIEU_DELIVRE_DOCS_GERAN"  ,
        "NUM_DOCS_GERAN"  ,
        "AUTRE_DOCS_GERAN"  ,
        "NATIONALITE_GERAN"  ,
        "ADRESSE_GERAN"  ,
        "CONTACT_GERAN"  ,
        "CONTACT_WHATSAPP_GERAN"  ,
        "NIVEAU_ETUDE_GERAN"  ,
        "CLASSE_GERAN"  ,
        "DIPLOME_ETD_OBT_GERAN"  ,
        "APPRENTISS_MET_GERAN"  ,
        "NIVEAU_METIER_GERAN"  ,
        "DIPLOME_MET_OBT_GERAN"  ,
        "DIPLOME_CNMCI_GERAN"  ,
        "ETAT_CIVIL_GERAN"  ,
        "ADR_EMAIL_GERAN"  ,
        "AVATAR_GERAN"  ,
        "DECLARE_MAITRISE_METIER" ,
        "DECLARE_NON_CONDAMNATION" ,
        "ACCEPTE_CONFIDENTIAL" ,
        "SIGNATURE"  ,
        "STATUT" ,
        "MOTIFS_REJET"  ,
        "created_at"  ,
        "updated_at"  ,
        "deleted_at"  ,
        "ID_AGENTS" ,
    ];
    use HasFactory;
}
